--- 
name: rubywaves.com
title: Ruby Waves
description: Waves is an open source framework for building Ruby-based Web-applications.
stylesheet: default
authors: 
- Dan Yoder
- Matthew King
administrators: 
- name: Dan Yoder
  password: zigzag9
  email: dan@zeraweb.com
administrators: 
- name: Dan Yoder
  password: zigzag9
  email: dan@zeraweb.com
- name: Matthew King
  email: automatthew@gmail.com
  password: ctfoeb