--- 
name: debugs
title: Debu.gs
domain: debu.gs
description: The next step in the evolution of user error.
authors: 
- Pete Elmore
administrators: 
- name: Pete Elmore
  password: fr33c0k3
  email: pete.elmore@gmail.com
roles:
- Admin

Admin:
- property
- story
- image
- blog
- gallery
