--- 
name: minipumpkins
title: Art Glass Mini-Pumpkins
domain: vaxpumpkins.com
description: High-quality art glass mini-pumpkins.
authors: 
- Vax
administrators: 
- name: Vax
  password: vax
  email: vaxbowes@yahoo.com
- name: Dan Yoder
  password: zigzag9
  email: dan@zeraweb.com
roles:
- Admin

Admin:
- property
- story
- image
- blog
- gallery
